proyecto/atletas/urls.py
from django.urls import path
from . import views

app_name = "atletas"

urlpatterns = [
    path("", views.index, name = "index"),
    path("pais/list", views.PaisList.as_view(), name = "pais_list"),
    path("pais/create", views.PaisCreate.as_view(), name = "pais_create"),
    path('atleta/detail/<int:pk>/',views.PaisDetail.as_view(),name='atleta_detail',), 
    path('atleta/update/<int:pk>/',views.PaisUpdate.as_view(),name='atleta_update',),
    path( 'atleta/delete/<int:pk>/', views.PaisDelete.as_view(), name='atleta_delete')
]

proyecto/home/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path('login', LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='home/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

proyecto/planes/urls.py
from django.urls import path
from . import views

app_name = 'planes'  

urlpatterns = [
    path('', views.index, name='index'),  
    path('asignar_plan/<int:atleta_id>/', views.asignar_plan, name='asignar_plan'),
    path('list/', views.plan_list, name='plan_list'),
    path('create/', views.plan_create, name='plan_create'),
    path('<int:id>/', views.plan_detail, name='plan_detail'),  
    path('plan/update/<int:pk>/', views.plan_update, name='plan_update'),
    path('delete/<int:id>/', views.plan_delete, name='plan_delete'),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('atletas/',include('atletas.urls')),
    path('planes/',include('planes.urls')),
    path('productos/',include('productos.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/planes/models.py
from django.db import models

class Plan(models.Model):
    ENTRENAMIENTO_CHOICES = [
        ('fuerza', 'fuerza'),
        ('resistencia', 'resistencia'),
        ('velocidad', 'velocidad'),
        ('potencia', 'potencia')
    ]
    entrenamiento = models.CharField(max_length=20, choices=ENTRENAMIENTO_CHOICES, null=False, blank=False)  
    
    DIAS_CHOICES = [
        ('1 a 3 dias', '1 a 3 dias'),
        ('3 a 5 dias', '3 a 5 dias'),
        ('5 a 7 dias', '5 a 7 dias')
    ]
    dias = models.CharField(max_length=20, choices=DIAS_CHOICES, null=False, blank=False)  

    HORAS_CHOICES = [
        ('menos de una hora', 'menos de una hora'),
        ('una a dos horas', 'una a dos horas'),
        ('mas de dos horas', 'mas de dos horas'),
    ]
    horas = models.CharField(max_length=30, choices=HORAS_CHOICES, null=False, blank=False)  
 

proyecto/planes/forms.py
# En forms.py
from django import forms
from .models import Plan

class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ['entrenamiento', 'dias', 'horas']  # Asegúrate de incluir todos los campos que deseas

proyecto/planes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from atletas.models import Pais
from planes.models import Plan 
from .forms import PlanForm 

def index(request):
    return render(request, 'planes/index.html')

def asignar_plan(request, atleta_id):
    atleta = get_object_or_404(Pais, id=atleta_id)
    
    if atleta.velocidad == '5.4 segundos o más':  
        plan = "Plan exigente de mejora en velocidad"
    elif atleta.velocidad == '5.0 - 5.3 segundos':
        plan= "Plan de mejora de velocidad"
    else:
        plan = "Plan de mantenimiento"

    context = {
        'atleta': atleta,
        'plan': plan,
    }

    return render(request, 'planes/asignar_plan.html', context)

def index_planes(request):
    planes = Plan.objects.all()  
    return render(request, 'planes/index.html', {'planes': planes})

def plan_list(request):
   
    planes = Plan.objects.all()
    return render(request, 'planes/plan_list.html', {'planes': planes})

def plan_create(request):
    if request.method == 'POST':
        form = PlanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('planes:plan_list') 

    else:
        form = PlanForm()
    return render(request, 'planes/plan_create.html', {'form': form})

def plan_detail(request, id):
    plan = get_object_or_404(Plan, id=id)
    return render(request, 'planes/plan_detail.html', {'plan': plan})

def plan_update(request, pk):
    plan = get_object_or_404(Plan, pk=pk)  

    if request.method == 'POST':
        form = PlanForm(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            return redirect('planes:plan_list')  
    else:
        form = PlanForm(instance=plan)

    return render(request, 'planes/plan_update.html', {'form': form})

def plan_delete(request, id):
    plan = get_object_or_404(Plan, id=id)

    if request.method == 'POST':
        plan.delete()
        return redirect('planes:index')  

    return render(request, 'planes/plan_confirm_delete.html', {'plan': plan})

proyecto/planes/templates/planes/asignar_plan.html
{% extends 'home/base.html' %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1 class="text-center mb-4">Asignar Plan</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container mt-5">
    <h2 class="text-success">Atleta: {{ atleta.nombre }}</h2>
    <p class="fs-5">Descripción: {{ atleta.velocidad}}</p>
    <h4 class="mt-4">Plan Asignado:</h4>
    <p class="fs-6">{{ plan }}</p>
    
    <div class="text-center mt-4">
        <button class="btn btn-secondary">
            <a class="text-white text-decoration-none" href="{% url 'atletas:pais_list' %}">Volver a la lista de Atletas</a>
        </button>
    </div>
</div>
{% endblock main %}

proyecto/planes/templates/planes/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block header %}
    <div class="bg-dark text-white text-center py-5">
        <h1>PLANES</h1>
    </div>
{% endblock header %}

{% block main %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4 mb-3">
                <a href="{% url 'planes:plan_create' %}" class="btn btn-success btn-block">Crear Plan</a>
            </div>
            <div class="col-md-4 mb-3">
                <a href="{% url 'planes:plan_list' %}" class="btn btn-dark btn-block">Lista de Planes</a>
            </div>
        </div>
    </div>
{% endblock main %}

proyecto/planes/templates/planes/plan_confirm_delete.html
{% extends 'home/base.html' %}
{% load static %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Eliminar Plan</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container bg-dark text-light py-4">
    <h3>¿Estás seguro de que deseas eliminar el plan "{{ plan.entrenamiento }}"?</h3>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar eliminación</button>
        <a href="{% url 'planes:index' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock main %}

proyecto/planes/templates/planes/plan_create.html
{% extends 'home/base.html' %}
{% load static %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Crear Plan</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container bg-dark text-light py-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'planes:plan_list' %}" class="btn btn-secondary">Volver</a>
    </form>
</div>
{% endblock main %}

proyecto/planes/templates/planes/plan_detail.html
{% extends 'home/base.html' %}
{% load static %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Detalles del Plan</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container bg-dark text-light py-4">
    <h2>{{ plan.entrenamiento }}</h2>
    <p><strong>Días:</strong> {{ plan.dias }}</p>
    <p><strong>Horas:</strong> {{ plan.horas }}</p>
    
    <a href="{% url 'planes:plan_update' plan.id %}" class="btn btn-secondary">Cambiar</a>
    <a href="{% url 'planes:plan_delete' plan.id %}" class="btn btn-danger">Eliminar</a>
    <a href="{% url 'planes:plan_list' %}" class="btn btn-primary">Volver a la lista</a>
</div>
{% endblock main %}

proyecto/planes/templates/planes/plan_list.html
{% extends 'home/base.html' %}
{% load static %}  

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Lista de Planes</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container bg-dark text-light py-4">  
    <form action="{% url 'planes:plan_list' %}" method="get" class="mb-4">
        <div class="input-group">
            <input type="text" name="q" placeholder="Buscar..." class="form-control">
            <button type="submit" class="btn btn-primary">Buscar</button>
            <button class="btn btn-success">
                <a href="{% url 'planes:plan_create' %}" class="text-white text-decoration-none">Crear Plan</a>
            </button>
        </div>
    </form>

    <ul class="list-group">
        {% for plan in planes %}
            <li class="list-group-item bg-secondary text-light">
                <strong>Entrenamiento:</strong> {{ plan.entrenamiento }}<br>
                <strong>Días:</strong> {{ plan.dias }}<br>
                <strong>Horas:</strong> {{ plan.horas }}
                <div class="mt-2">
                    <a class="btn btn-success btn-sm" href="{% url 'planes:plan_detail' plan.id %}">Más datos</a>
                    <a class="btn btn-secondary btn-sm" href="{% url 'planes:plan_update' plan.id %}">Modificar</a>
                    <a class="btn btn-danger btn-sm" href="{% url 'planes:plan_delete' plan.id %}">Eliminar</a>
                </div>
            </li>
        {% empty %}
            <li class="list-group-item text-center">No hay planes disponibles.</li>
        {% endfor %}
    </ul>

    <button class="btn btn-secondary mt-3">
        <a class="text-white text-decoration-none" href="{% url 'planes:index' %}">Volver</a>
    </button>
</div>
{% endblock main %}

proyecto/planes/templates/planes/plan_update.html
{% extends 'home/base.html' %}
{% load static %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Actualizar Plan</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container bg-dark text-light py-4">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        <a href="{% url 'planes:plan_list' %}" class="btn btn-secondary">Volver</a>
    </form>
</div>
{% endblock main %}