proyecto/atletas/urls.py
from django.urls import path
from . import views

app_name = "atletas"

urlpatterns = [
    path("", views.index, name = "index"),
    path("pais/list", views.PaisList.as_view(), name = "pais_list"),
    path("pais/create", views.PaisCreate.as_view(), name = "pais_create"),
    path('atleta/detail/<int:pk>/',views.PaisDetail.as_view(),name='atleta_detail',), 
    path('atleta/update/<int:pk>/',views.PaisUpdate.as_view(),name='atleta_update',),
    path( 'atleta/delete/<int:pk>/', views.PaisDelete.as_view(), name='atleta_delete')
]

proyecto/home/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path('login', LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='home/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

proyecto/planes/urls.py
from django.urls import path
from . import views

app_name = 'planes'  

urlpatterns = [
    path('', views.index, name='index'),  
    path('asignar_plan/<int:atleta_id>/', views.asignar_plan, name='asignar_plan'),
    path('list/', views.plan_list, name='plan_list'),
    path('create/', views.plan_create, name='plan_create'),
    path('<int:id>/', views.plan_detail, name='plan_detail'),  
    path('plan/update/<int:pk>/', views.plan_update, name='plan_update'),
    path('delete/<int:id>/', views.plan_delete, name='plan_delete'),
]

proyecto/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
   path("productos", views.index, name = "index"),
   path("productocategoria/list", views.ProductoCategoriaList.as_view(), name = 'productocategoria_list',),
   path("productocategoria/create", views.ProductoCategoriaCreate.as_view(), name = "productocategoria_create"),
   path(
       'productocategoria/detail/<int:pk>/',
       views.ProductoCategoriaDetail.as_view(),
       name='productocategoria_detail',
        ),
    path(
       'productocategoria/update/<int:pk>/',
       views.ProductoCategoriaUpdate.as_view(),
       name='productocategoria_update',
        ),
    path(
        'productocategoria/delete/<int:pk>/',
        views.ProductoCategoriaDelete.as_view(),
        name='productocategoria_delete'
    )
  
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('atletas/',include('atletas.urls')),
    path('planes/',include('planes.urls')),
    path('productos/',include('productos.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/home/models.py
from django.db import models

# Create your models here.

proyecto/home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name','email')

proyecto/home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import CustomUserCreationForm, UserProfileForm

def index(request):
    return render(request, 'home/index.html')


class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = "home/register.html"
    success_url = reverse_lazy('home:login')

class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'home/profile.html'
    success_url = reverse_lazy('home:index')
    
    def get_object(self):
        return self.request.user

proyecto/home/templates/home/componentes/footer.html
<footer class="bg-dark py-2 fixed-bottom">
    <div class="container px-5">
        <div class="col-auto">
            <div class="small m-0 text-white text-center">Copyright &copy; 2024</div>
        </div>
    </div>
</footer>

proyecto/home/templates/home/componentes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-5">
      <a class="navbar-brand" href="{% url 'home:index' %}">NEXUS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item"><a class="nav-link" href="{% url 'home:index' %}">🏠Home</a></li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'atletas:index' %}">Atletas</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'planes:index' %}">Planes</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'productos:index' %}">Productos</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'home:profile' %}">{{ user.username }}</a></li>
                  {% if user.vendedor.avatar %}
                  <img src="{{ user.vendedor.avatar.url }}" alt="avatar" style="height: 30px;">
                  {% else %}
                  <img src="" alt="avatar" style="height: 30px;"> 
                  {% endif %}
              <li class="nav-item">
                <form action="{% url 'home:logout' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button class="btn nav-link" type="submit">Logout</button>
                </form>
              </li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'home:login' %}">Login</a></li>
              {% endif %}
          </ul>
      </div>
  </div>
</nav>