proyecto/home/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path('login', LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='home/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

proyecto/productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
   path("productos", views.index, name = "index"),
   path("productocategoria/list", views.ProductoCategoriaList.as_view(), name = 'productocategoria_list',),
   path("productocategoria/create", views.ProductoCategoriaCreate.as_view(), name = "productocategoria_create"),
   path(
       'productocategoria/detail/<int:pk>/',
       views.ProductoCategoriaDetail.as_view(),
       name='productocategoria_detail',
        ),
    path(
       'productocategoria/update/<int:pk>/',
       views.ProductoCategoriaUpdate.as_view(),
       name='productocategoria_update',
        ),
    path(
        'productocategoria/delete/<int:pk>/',
        views.ProductoCategoriaDelete.as_view(),
        name='productocategoria_delete'
    )
  
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('atletas/',include('atletas.urls')),
    path('planes/',include('planes.urls')),
    path('productos/',include('productos.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/productos/models.py
from django.db import models

class ProductoCategoria(models.Model):

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.nombre}"

    class Meta:
        verbose_name = 'Categoria de Producto'
        verbose_name_plural = 'Categorias de Productos'


class Producto(models.Model):
    categoria = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='categoria')
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    unidad_de_medida = models.CharField(max_length=50)
    stock = models.FloatField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_actualizacion = models.DateTimeField(editable=False, auto_now=True)

    def __str__(self) -> str:
        return f'{self.nombre}({self.unidad_de_medida}) ${self.precio:.2f}'
    
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        unique_together = ('categoria', 'nombre')

proyecto/productos/forms.py
from django import forms
from .models import ProductoCategoria
from django.core.exceptions import ValidationError

class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = ProductoCategoria
        fields = '__all__'

    def clean_nombre(self):
        nombre: str = self.cleaned_data.get('nombre','')

        if not nombre.isalpha():
            raise ValidationError('El nombre solo puede contener letras')
     
        if len(nombre) < 3 or len(nombre) > 50:
            raise ValidationError("El nombre debe tener una longitud minima de 3 letras o maxima de 50")
        return nombre

proyecto/productos/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import ProductoCategoria
from .forms import ProductoCategoriaForm

def index(request):
    return render(request, 'productos/index.html')

class ProductoCategoriaList(ListView):
    model = ProductoCategoria
    context_object_name = 'productocategorias' #De forma predeterminada es 'object_list'
    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = ProductoCategoria.objects.filter(nombre__icontains=q)
        return queryset
    

class ProductoCategoriaCreate(CreateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy('productos:productocategoria_list')


class ProductoCategoriaDetail(DetailView):
    model = ProductoCategoria
  

class ProductoCategoriaUpdate(UpdateView):
    model = ProductoCategoria
    form_class = ProductoCategoriaForm
    success_url = reverse_lazy("productos:productocategoria_list")


class ProductoCategoriaDelete(DeleteView):
    model = ProductoCategoria
    success_url = reverse_lazy('productos:productocategoria_list')

proyecto/productos/templates/productos/index.html
{% extends 'home/base.html' %}
{% block header %}
    <div class="bg-dark text-white text-center py-5">
      <h1>PRODUCTOS</h1>
    </div>
{% endblock header %}
{% block main %}
    <div class="container mt-5">
      <div class="row justify-content-center">
          <div class="col-md-4 mb-3">
              <a href="{% url 'productos:productocategoria_list' %}"class="btn btn-success btn-block">Lista Productos</a>
          </div>
          <div class="col-md-4 mb-3">
              <a href="{% url 'productos:productocategoria_create' %}" class="btn btn-dark btn-block">Crear Productos</a>
          </div>
      </div>
    </div> 
{% endblock main %}
   
    
   

proyecto/productos/templates/productos/productocategoria_confirm_delete.html
{% extends 'home/base.html' %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
  <h1 class="text-center mb-4">Borrar Producto</h1>
</div>
{% endblock header %}
   

{% block main %}
<div class="container text-center mb-4">
   <p class="fs-3">¿Estas seguro que desea borrar el producto "{{object.nombre}}"?</p>
   <form method="post" class="mb-4">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirmar</button>
   </form>
   
    <button class="btn btn-secondary"><a class="text-white text-decoration-none" href="{% url 'productos:productocategoria_list' %}">Volver</a></button>
</div>
{% endblock main  %}
    

proyecto/productos/templates/productos/productocategoria_detail.html
{% extends 'home/base.html' %}
{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1> Vista en detalle del producto</h1>
</div>
{% endblock header %}
{% block main %}
<section class="container mb-4">
    <ul class="list-group">
        <li class="list-group-item">Nombre: {{object.nombre}}</li>
        <li class="list-group-item">Descripcion: {{object.descripcion}}</li>
    </ul>
</section>
    <div class="text-center">
        <button class="btn btn-secondary"><a class="text-white text-decoration-none" href="{% url 'productos:productocategoria_list' %}">Volver</a></button>
    </div>
{% endblock main  %}
    

proyecto/productos/templates/productos/productocategoria_form.html
{% extends 'home/base.html' %}
{% load widget_tweaks %}

{% block header %}
    {% if form.instance.pk %}
        <div class="bg-dark text-white text-center py-5">
            <h1> Actualizar producto</h1>
        </div>
    {% else %}
        <div class="bg-dark text-white text-center py-5">
            <h1> Crear nuevo producto</h1>
        </div>
    {% endif %}
{% endblock header %}
{% block main %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nombre" class="form-label fs-5">Nombre</label>
            {{ form.nombre|add_class:"form-control" }}
          </div>
        <div class="mb-3">
            <label for="id_descripcion" class="form-label fs-5">Descripción</label>
            {{ form.descripcion|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary fs-5">Enviar</button>
    </form>

    <button  class="btn btn-secondary mt-3"><a  class="text-white text-decoration-none fs-5" href="{% url 'productos:productocategoria_list' %}">Volver</a></button>
</div>
{% endblock main  %}
    

proyecto/productos/templates/productos/productocategoria_list.html
{% extends 'home/base.html' %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Lista de Productos</h1>
</div>
{% endblock header %}

{% block main %}
<div class="bg-dark text-light py-4">
    <div class="container">
        <form action="{% url 'productos:productocategoria_list' %}" method="get" class="mb-3">
            <div class="input-group">
                <input type="text" name="q" placeholder="Buscar..." class="form-control">
                <button type="submit" class="btn btn-primary">Buscar</button>
                <button class="btn btn-success">
                    <a href="{% url 'productos:productocategoria_create' %}" class="text-white text-decoration-none">Crear Registro</a>
                </button>
            </div>
        </form>

        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th style="width: 20%;">Nombre</th>
                    <th style="width: 30%;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productocategorias %}
                <tr>
                    <td>{{ producto.nombre }}</td>
                    <td>
                        <button class="btn btn-success btn-sm me-2">
                            <a class="text-white text-decoration-none" href="{% url 'productos:productocategoria_detail' producto.id %}">Más detalle</a>
                        </button>
                        <button class="btn btn-secondary btn-sm me-2">
                            <a class="text-white text-decoration-none" href="{% url 'productos:productocategoria_update' producto.id %}">Cambiar</a>
                        </button>
                        <button class="btn btn-danger btn-sm">
                            <a class="text-white text-decoration-none" href="{% url 'productos:productocategoria_delete' producto.id %}">Eliminar</a>
                        </button>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">No hay registros</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-secondary">
            <a href="{% url 'productos:index' %}" class="text-white text-decoration-none">Volver</a>
        </button>
    </div>
</div>
{% endblock main %}