proyecto/atletas/urls.py
from django.urls import path
from . import views

app_name = "atletas"

urlpatterns = [
    path("", views.index, name = "index"),
    path("pais/list", views.PaisList.as_view(), name = "pais_list"),
    path("pais/create", views.PaisCreate.as_view(), name = "pais_create"),
    path('atleta/detail/<int:pk>/',views.PaisDetail.as_view(),name='atleta_detail',), 
    path('atleta/update/<int:pk>/',views.PaisUpdate.as_view(),name='atleta_update',),
    path( 'atleta/delete/<int:pk>/', views.PaisDelete.as_view(), name='atleta_delete')
]

proyecto/home/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path('login', LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='home/logout.html'), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.Profile.as_view(), name='profile'),
]

urlpatterns += staticfiles_urlpatterns()

proyecto/planes/urls.py
from django.urls import path
from . import views

app_name = 'planes'  

urlpatterns = [
    path('', views.index, name='index'),  
    path('asignar_plan/<int:atleta_id>/', views.asignar_plan, name='asignar_plan'),
    path('list/', views.plan_list, name='plan_list'),
    path('create/', views.plan_create, name='plan_create'),
    path('<int:id>/', views.plan_detail, name='plan_detail'),  
    path('plan/update/<int:pk>/', views.plan_update, name='plan_update'),
    path('delete/<int:id>/', views.plan_delete, name='plan_delete'),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('atletas/',include('atletas.urls')),
    path('planes/',include('planes.urls')),
    path('productos/',include('productos.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/atletas/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    apellido = models.CharField(max_length=50)
    edad = models.PositiveIntegerField(null=True, blank=True)  
    peso = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True) 
    altura = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)  
    SEXO_CHOICES = [
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
        ('Otro', 'Otro'),
    ]
    sexo = models.CharField(max_length=10, choices=SEXO_CHOICES, null=True, blank=True)  
    DEPORTE_CHOICES = [
        ('Futbol', 'Futbol'),
        ('Rugby', 'Rugby'),
        ('Basquet', 'Basquet'),
        ('Tenis', 'Tenis'),
        ('Atletismo', 'Atletismo'),
    ]
    deporte = models.CharField(max_length=10, choices=DEPORTE_CHOICES, null=True, blank=True) 
    GRASA_CHOICES = [
        ('6-13%','6-13%'),
        ('14-17%','14-17%'),
        ('18-24%','18-24%'),
        ('25% o mas','25% o mas'),
    ] 
    grasa = models.CharField(max_length=10, choices=GRASA_CHOICES, null=True, blank=True)

    VELOCIDAD_CHOICES = [
        ('4.6 - 4.9 segundos',' 4.6 - 4.9 segundos'),
        ('5.0 - 5.3 segundos','5.0 - 5.3 segundos' ),
        ('5.4 segundos o más', '5.4 segundos o más' ,),
    ]
    velocidad = models.CharField(max_length=20, choices=VELOCIDAD_CHOICES, null=True, blank=True)

    descripcion = models.TextField(null=True, blank=True)  

proyecto/atletas/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Pais

class PaisForm(forms.ModelForm):
    class Meta:
        model = Pais
        fields = '__all__'

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre', '').strip()  
        nombre = nombre.capitalize()
        
        if not nombre.isalpha():
            raise ValidationError('El nombre solo puede contener letras.')

        if len(nombre) < 3 or len(nombre) > 50:
            raise ValidationError('El nombre debe tener una longitud mínima de 3 letras y máxima de 50.')

        return nombre

    def clean_apellido(self):
        apellido = self.cleaned_data.get('apellido', '').strip()  
        apellido = apellido.capitalize()

        if not apellido.isalpha():
            raise ValidationError('El apellido solo puede contener letras.')

        if len(apellido) < 3 or len(apellido) > 50:
            raise ValidationError('El apellido debe tener una longitud mínima de 3 letras y máxima de 50.')

        return apellido

proyecto/atletas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import DeleteView, ListView, CreateView, DetailView,UpdateView
from django.urls import reverse_lazy
from .forms import PaisForm
from .models import Pais

def index(request):
    return render(request, 'atletas/index.html')

class PaisList(LoginRequiredMixin, ListView):
    model = Pais
    context_object_name = 'paises'
    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = Pais.objects.filter(nombre__icontains=q)
        return queryset

class PaisCreate(LoginRequiredMixin, CreateView):
    model = Pais
    form_class = PaisForm
    success_url = reverse_lazy('atletas:pais_list')


class PaisDetail(LoginRequiredMixin, DetailView):
    model = Pais
    template_name = 'atletas/pais_detail.html' 
    context_object_name = 'pais'  

    

class PaisUpdate(LoginRequiredMixin, UpdateView):
    model = Pais
    form_class = PaisForm
    success_url = reverse_lazy('atletas:pais_list')


class PaisDelete(LoginRequiredMixin, DeleteView):
    model = Pais
    success_url = reverse_lazy('atletas:pais_list')

proyecto/atletas/templates/atletas/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block header %}
    <div class="bg-dark text-white text-center py-5">
        <h1>ATLETAS</h1>
    </div>
{% endblock header %}

{% block main %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4 mb-3">
                <a href="{% url 'atletas:pais_create' %}" class="btn btn-success btn-block">Registrar Atletas</a>
            </div>
            <div class="col-md-4 mb-3">
                <a href="{% url 'atletas:pais_list' %}" class="btn btn-dark btn-block">Lista de Atletas</a>
            </div>
        </div>
    </div>
{% endblock main %}


    
   
  

proyecto/atletas/templates/atletas/pais_confirm_delete.html
{% extends 'home/base.html' %}

{% block header %}
<div class="bg-dark text-white text-center py-5">
  <h1 class="text-center mb-4">Borrar Atleta</h1>
</div>
{% endblock header %}

{% block main %}
  <div class="container text-center mb-4">
    <p class="fs-3">¿Estás seguro que deseas borrar al atleta "{{ pais.nombre }} {{ pais.apellido }}"?</p>
    <form method="post" class="mb-4">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <button class="btn btn-secondary">
      <a class="text-white text-decoration-none" href="{% url 'atletas:pais_list' %}">Volver</a>
    </button>
  </div>
{% endblock main %}

    

proyecto/atletas/templates/atletas/pais_detail.html
{% extends 'home/base.html' %}
{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Datos del Atleta</h1>
</div>
    
{% endblock header %}

{% block main %}
<section class="container mb-4">
    <h2 class="text-success">Datos Básicos</h2>
    <ul class="list-group">
        <li class="list-group-item">Nombre: {{ object.nombre }}</li>
        <li class="list-group-item">Apellido: {{ object.apellido }}</li>
        <li class="list-group-item">Edad: {{ object.edad }}</li>
        <li class="list-group-item">Peso: {{ object.peso }}</li>
        <li class="list-group-item">Altura: {{ object.altura }}</li>
        <li class="list-group-item">Sexo: {{ object.sexo }}</li>
        <li class="list-group-item">Deporte: {{ object.deporte }}</li>
    </ul>
</section>

<section class="container mb-4">
    <h2 class="text-success">Condición Física</h2>
    <ul class="list-group">
        <li class="list-group-item">% de grasa corporal: {{ object.grasa }}</li>
        <li class="list-group-item">Test de 40 metros: {{ object.velocidad }}</li>
    </ul>
</section>

<section class="container mb-4">
    <h3 class="text-success">Objetivos</h3>
    <ul class="list-group">
        <li class="list-group-item">{{ object.descripcion }}</li>
    </ul>
</section>

<div class="text-center">
    
    <button class="btn btn-secondary">
        <a class="text-white text-decoration-none" href="{% url 'atletas:pais_list' %}">Volver</a>
    </button>
    <button class="btn btn-secondary">
        <a class="text-white text-decoration-none" href="{% url 'planes:asignar_plan' pais.id %}">Ver Plan</a>
    </button>
    
</div>
{% endblock main %}

proyecto/atletas/templates/atletas/pais_form.html
{% extends 'home/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block header %}
  {% if form.instance.pk %}
      <div class="bg-dark text-white text-center py-5">
        <h1>Actualizar Atleta</h1>
      </div>
  {% else %}
      <div class="bg-dark text-white text-center py-5">
        <h1>Registrar Atleta</h1>
      </div>
  {% endif %}
{% endblock header %}

{% block main %}
  <div class="container">
    <form method="post">
      {% csrf_token %}
      <h2 class="mt-4">Datos Básicos</h2>
      <div class="mb-3">
        <label for="id_nombre" class="form-label fs-5">Nombre</label>
        {{ form.nombre|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_apellido" class="form-label fs-5">Apellido</label>
        {{ form.apellido|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_edad" class="form-label fs-5">Edad</label>
        {{ form.edad|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_peso" class="form-label fs-5">Peso</label>
        {{ form.peso|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_altura" class="form-label fs-5">Altura</label>
        {{ form.altura|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_sexo" class="form-label fs-5">Sexo</label>
        {{ form.sexo|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_deporte" class="form-label fs-5">Deporte</label>
        {{ form.deporte|add_class:"form-control" }}
      </div>
      

      <h2 class="mt-4">Condición Física</h2>
      <div class="mb-3">
        <label for="id_grasa" class="form-label fs-5">% de grasa corporal</label>
        {{ form.grasa|add_class:"form-control" }}
      </div>
      <div class="mb-3">
        <label for="id_velocidad" class="form-label fs-5">Test en 40 metros</label>
        {{ form.velocidad|add_class:"form-control" }}
      </div>

      <h3 class="mt-4">Objetivos</h3>
      <div class="mb-3">
        <label for="id_descripcion" class="form-label fs-5">Descripción</label>
        {{ form.descripcion|add_class:"form-control" }}
      </div>

      <button type="submit" class="btn btn-primary fs-5">Enviar</button>
    </form>

    <button class="btn btn-secondary mt-3">
      <a class="text-white text-decoration-none fs-5" href="{% url 'atletas:index' %}">Volver</a>
    </button>
      
{% endblock main %}

proyecto/atletas/templates/atletas/pais_list.html
{% extends 'home/base.html' %}
{% load static %}  

{% block header %}
<div class="bg-dark text-white text-center py-5">
    <h1>Lista de Atletas</h1>
</div>
{% endblock header %}

{% block main %}
<div class="container bg-dark text-light py-4">  
    <form action="{% url 'atletas:pais_list' %}" method="get" class="mb-4">
        <div class="input-group">
            <input type="text" name="q" placeholder="Buscar..." class="form-control">
            <button type="submit" class="btn btn-primary">Buscar</button>
            <button class="btn btn-success">
                <a href="{% url 'atletas:pais_create' %}" class="text-white text-decoration-none">Crear Registro</a>
            </button>
        </div>
    </form>

    <table class="table table-striped table-dark">  
        <thead class="thead-dark">
            <tr>
                <th style="width: 30%;">Nombre</th>
                <th style="width: 10%;">Acciones</th>
                <th style="width: 10%;">Acciones</th>
                <th style="width: 10%;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for pais in paises %}
                <tr class="text-light">
                    <td>{{ pais.nombre }} {{ pais.apellido }}</td>
                    <td>
                        <a class="btn btn-success btn-sm" href="{% url 'atletas:atleta_detail' pais.id %}">Más datos</a>
                    </td>
                    <td>
                        <a class="btn btn-secondary btn-sm" href="{% url 'atletas:atleta_update' pais.id %}">Cambiar</a>
                    </td>
                    <td>
                        <a class="btn btn-danger btn-sm" href="{% url 'atletas:atleta_delete' pais.id %}">Eliminar</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No hay registros.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <button class="btn btn-secondary">
        <a class="text-white text-decoration-none" href="{% url 'atletas:index' %}">Volver</a>
    </button>
</div>
{% endblock main %}